/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConceptRouteImport } from './routes/concept'
import { Route as IndexRouteImport } from './routes/index'

const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptRoute = ConceptRouteImport.update({
  id: '/concept',
  path: '/concept',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concept': typeof ConceptRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/panier': typeof PanierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concept': typeof ConceptRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/panier': typeof PanierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concept': typeof ConceptRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/panier': typeof PanierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/concept' | '/contact' | '/menu' | '/panier'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/concept' | '/contact' | '/menu' | '/panier'
  id: '__root__' | '/' | '/concept' | '/contact' | '/menu' | '/panier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConceptRoute: typeof ConceptRoute
  ContactRoute: typeof ContactRoute
  MenuRoute: typeof MenuRoute
  PanierRoute: typeof PanierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept': {
      id: '/concept'
      path: '/concept'
      fullPath: '/concept'
      preLoaderRoute: typeof ConceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConceptRoute: ConceptRoute,
  ContactRoute: ContactRoute,
  MenuRoute: MenuRoute,
  PanierRoute: PanierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
